language: generic
sudo: false
before_install:
  - travis_retry curl "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" > miniconda.sh && chmod +x miniconda.sh && ./miniconda.sh -b -p "${HOME}/miniconda"
  - export PATH="${HOME}/miniconda:${PATH}"
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install

env:
  # TODO: this currently falls down installing `pythonic`, make it
  # work again somehow
  # - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.2-travis
script:
  - make test
